# -*- coding: utf-8 -*-
"""HongKong-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lr4g6-iCZM7vdZQ_FHbjDJ9QKLcyonV0
"""

pip install meteostat pandas

from datetime import datetime
import pandas as pd

start = datetime(1990, 1, 1)
end = datetime(2025, 8, 23)

location_id = '45007'  # Replace with the desired weather station ID

data = mt.Daily(location_id, start, end)
data = data.fetch()

df = pd.DataFrame(data)

print(df.head())

print(df.columns)

import pandas as pd

# Sample data
data = {
    'Year': [1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999],
    'Average_Temperature': [23.5, 23.8, 24.0, 24.5, 25.0, 25.3, 25.7, 26.0, 26.5, 26.8]
}

# Create DataFrame
df = pd.DataFrame(data)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Ensure 'Year' and 'Average_Temperature' columns exist
if 'Year' in df.columns and 'Average_Temperature' in df.columns:
    years = df['Year'].values.reshape(-1, 1)
    temperatures = df['Average_Temperature'].values

    # Fit the linear regression model
    model = LinearRegression()
    model.fit(years, temperatures)

    # Predict values
    predicted_temperatures = model.predict(years)

    # Plotting
    plt.figure(figsize=(10, 6))
    plt.scatter(years, temperatures, color='blue', label='Actual Data')
    plt.plot(years, predicted_temperatures, color='red', label='Trend Line', linewidth=2)
    plt.title('Average Temperature Over Time')
    plt.xlabel('Year')
    plt.ylabel('Average Temperature (°C)')
    plt.legend()
    plt.grid()
    plt.show()
else:
    print("DataFrame must contain 'Year' and 'Average_Temperature' columns.")

print(df.columns)

df.describe()

df['time_dt'] = pd.to_datetime(df.index)
df['months'] = (df['time_dt']).dt.month
df